// <auto-generated />
namespace Ninhao.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ninhao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ninhao));
        
        string IMigrationMetadata.Id
        {
            get { return "202008121739382_ninhao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
